### ISSUE TITLE
Make keyboard not clip through floor on really small avatars

### ISSUE THREAD

**Issue by FairlySadPanda** [FairlySadPanda/UdonStringEvents#2]

**Comment by retroheim** [comment]
There's a couple ways of doing it, namely getting how high the head of the player's avatar is and adjust if it is below a certain threshold or getting the player's head and hands and making a scale using a switch statement for all of them and using that to scale the keyboard to the avatar. 

This is just what I can think of at the top of my head, the first way would be more performance friendly while the second one would be more accurate.

**Comment by FairlySadPanda** [comment]
Fixed in 9b0c0b8a132c3955d7dc39c82b375bb104ccff59.
